---
title: "PS270 Final Project"
author: "Jonah Frumkin"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Milestone 1 (project thoughts)

I am interested in exploring data related to the effects of gender, race/ethnicity, SES, and parent education level on a student's standardized exam or on how frequently a student is suspended/expelled from school.

## Milestone 2 

My research question will be, what is the effect of zip code and racial/ethnic percentage of a school on its SAT scores. My hypothesis is that schools with a higher percentage of Black and Hispanic students will perform worse because of the long-lasting effects of racist practices such as segregation and racial biases in terms of housing, education, and employment. The independent variables will be a school's zip code and its racial/ethnic percentage because these two variables can be tied to each other due to residential segregation efforts in the past. The race/ethnicity of a school will be calculated by counting the total number of students and then finding the percentage of different student demographics. The zipcode is determined by the geographical boundaries of which the school is in and that will be represented by a five digit code. An observed pattern that would prove my hypothesis to be true is if schools with higher percentages of students that are Black or Hispanic are found to have relatively lower SAT scores on the math and reading sections. Another pattern that would prove my hypothesis to be true is if there were distinct variations in SAT math and reading scores between different zip codes and those various zip codes are associated with different percentages of Black and Hispanic students. An observed pattern that would disprove this hypothesis would be if there was no general distinction in SAT scores between schools that had different proportions of Black and Hispanic students as well as not having a great variation in SAT scores between different zip codes.

